Repository red-hat-storage/mcg-osd-deployer, pull requests merged in 2022-08, with the labels that each got.

#65 RHOBS support
  config/manager/manager.yaml
  controllers/managedmcg_controller.go
  controllers/managedmcg_controller_test.go
  controllers/monitoring_alert.go
  main.go
  templates/prometheus.go
Labels: lgtm, approved, needs-ok-to-test

#69 [DFMS-220] Generate variant and env labels dynamically
  controllers/monitoring_alert.go
Labels: lgtm, approved

#73 DFMS-229: addon uninstall is not removing all the resources
  controllers/managedmcg_controller.go
  controllers/mcg_bucket.go
Labels: lgtm, approved

#74 [DFMS-245] : Data Federation security Vulnerabilities - fix
  bundle/manifests/mcg-osd-deployer.clusterserviceversion.yaml
  config/console/console_init.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
  controllers/monitoring_alert.go
  go.mod
  go.sum
  hack/deploy/addonconfigmap.yaml
  vendor/gopkg.in/yaml.v3/decode.go
  vendor/gopkg.in/yaml.v3/parserc.go
  vendor/modules.txt
Labels: lgtm, approved

#78 Add documentation.
  CONTRIBUTING.md
  README.md
Labels: lgtm, approved

#79 Fix typo
  README.md
Labels: approved

#76 Added Status check for mcg-ms-console pod
  api/v1alpha1/managedmcg_types.go
  api/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/mcg.openshift.io_managedmcgs.yaml
  controllers/managedmcg_controller.go
  readinessProbe/readiness/server.go
Labels: lgtm, approved

#75 Fix remote write alerts for RHOBS
  templates/alertmanagerconfig.go
  templates/prometheus.go
  utils/utils.go
Labels: lgtm

#80 Remove EgressNetworkPolicy dependency
  config/rbac/role.yaml
  controllers/managedmcg_controller.go
  controllers/managedmcg_controller_test.go
  shim/crds/egressnetworkpolicies.network.openshift.io.yaml
  templates/egressnetworkpolicy.go
Labels: lgtm, approved

#82 remove egressnetworkpolicies from bundle
  bundle/manifests/mcg-osd-deployer.clusterserviceversion.yaml
Labels: lgtm, approved

#84 remove apiGroup for egressnetworkpolicies
  bundle/manifests/mcg-osd-deployer.clusterserviceversion.yaml
Labels: lgtm, approved

#83 complete cleanup of egress network policy
  config/rbac/role.yaml
Labels: lgtm, approved

#86 remove compatible basepath code
  console/console.go
  controllers/managedmcg_controller.go
Labels: lgtm, approved

#81 Infer variant value from the addon name.
  main.go
Labels: lgtm, approved

#87 Updated SMTP alerts mail content
  templates/customernotification.html
Labels: lgtm, approved

#88 upgrade to mcg version 4.11
  bundle/manifests/mcg-osd-deployer.clusterserviceversion.yaml
  bundle/manifests/mcg.openshift.io_managedmcgs.yaml
  bundle/metadata/dependencies.yaml
  config/crd/bases/mcg.openshift.io_managedmcgs.yaml
  config/metadata/dependencies.yaml
  config/rbac/role.yaml
  controllers/managedmcg_controller.go
  hack/deploy/prometheus.yaml
  templates/noobaa.go
  templates/prometheus.go
Labels: lgtm, approved
